### ISSUE TITLE
Problemy przy tworzeniu projektu

### ISSUE THREAD

**Issue by HubertSadecki** [BDIOL81/Projekt_BDIO#1]
NIE MOŻE ODNALEŹĆ TEMPLATE:
do pliku settings.py dodajemy

PATH_PROJECT = os.path.realpath(os.path.dirname(\__file__))
TEMPLATE_DIRS =( 
PATH_PROJECT+"/templates",
)

BUDOWANIE BAZY DANYCH:
(projekt to nazwa naszego projektu, może się różnić)
do pliku setting.py w INSTALLED_APPS dopisujemy 'projekt', 
teraz z konsoli wywołujemy polecenie 
1. python manage.py makemigrations projekt
2. python manage.py migrate

Teraz mamy stworzoną bazę danych

WCZYTANIE PLIKU CSS
Dodajemy do settings.py:

PROJECT_DIR = os.path.dirname(os.path.abspath(\__file__))
STATICFILES_DIRS = (
    os.path.join(PROJECT_DIR, 'static'),
)

**Comment by tkbdragin** [comment]
Myślę, że wszyscy już projekt utworzyli.
