### ISSUE TITLE
Uprawnienia użytkowników

### ISSUE THREAD

**Issue by RowinskiAdam** [BDIOL81/Projekt_BDIO#2]
Pokrótce chodzi o to że w panelu zarządzania wyświetlają się linki do odpowiednich podstron z funkcjonalnościami. Jednak nie każdy powinien mieć dostęp do nich, co za czym idzie nie każdemu powinny się wyświetlać więc teraz pojawia się problem kto powinien mieć jakie uprawnienia.

Wszystko poniżej jak dla mnie to tylko dla canManage:
Zniżki
Kategorie produktów
Typy użytkowników
Użytkownicy
Składniki
Produkty

Są jeszcze funkcjonalności które tutaj nie widnieją, dlatego też trzeba ustalić, co jest dla kogo oraz dodać te których niema i je również określić.

**Comment by HubertSadecki** [comment]
Składniki -> canEdit, canManage
